import 'package:art_events/dummy_user.dart';
import './models/event.dart';




const DUMMY_EVENTS = const [
 Event(
   id: 'Ev1',
   name: 'Performance Christian Marclay',
   place: 'Bâle',
   date: '26 janvier',
   hour: '19h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/shuerpf.jpg',
 ),
 Event(
   id: 'Ev2',
   name: 'Beyeler Foundation Georg Baselitz',
   place: 'Bâle',
   date: '21 janvier',
   hour: '18h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/beyeler.jpg',
 ),
 Event(
   id: 'Ev3',
   name: 'Art-à-Porter',
   place: 'Genève',
   date: '31 janvier',
   hour: '10h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/artAporter.jpg',
 ),
 Event(
   id: 'Ev4',
   name: 'Olafur Eliasson: Objects efined by activity',
   place: 'Genève',
   date: '23 janvier',
   hour: '18h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/eliasson.jpg',
 ),
 Event(
   id: 'Ev5',
   name: 'Engadin Art Talks',
   place: 'Zürich',
   date: '27 janvier',
   hour: '16h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/EngadinArtTalks.jpg',
 ),
 Event(
   id: 'Ev6',
   name: 'Artgenève',
   place: 'Genève',
   date: '1 février',
   hour: '20h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/artGeneve.jpg',
 ),
 Event(
   id: 'Ev7',
   name: 'Abraham Cruzvillegas: Social Tissue',
   place: 'Zürich',
   date: '16 février',
   hour: '18h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/cruzvillegas.jpg',
 ),
 Event(
   id: 'Ev8',
   name: 'Museumnight Bern',
   place: 'Berne',
   date: '16 mars',
   hour: '18h00',
   participants: DUMMY_USERS,
   responsable: ORGA,
   image: 'assets/images/museumNight.jpg',
 ),
];