import 'package:art_events/dummy_users.dart';
import 'package:art_events/widgets/event_item.dart';
import './models/event.dart';

const DUMMY_EVENTS = const [
  EventItem(
   // id: 'Ev1',
    name: 'Performance Christian Marclay',
    place: 'Bâle',
    date: '26.01.2022',
    hour: '19h00',
  //  participants: DUMMY_USERS,
  //  responsable: ORGA,
    image: 'assets/images/schuerpf.jpg',
  ),
  EventItem(
 //   id: 'Ev2',
    name: 'Beyeler Foundation Georg Baselitz',
    place: 'Bâle',
    date: '21.01.2022',
    hour: '18h00',
//    participants: DUMMY_USERS,
//    responsable: ORGA,
    image: 'assets/images/beyeler.jpg',
  ),
  EventItem(
 //   id: 'Ev3',
    name: 'Art-à-Porter',
    place: 'Genève',
    date: '31.01.2022',
    hour: '10h00',
    // participants: DUMMY_USERS,
    // responsable: ORGA,
    image: 'assets/images/artAporter.jpg',
  ),
  EventItem(
//    id: 'Ev4',
    name: 'Olafur Eliasson: Objects efined by activity',
    place: 'Genève',
    date: '23.01.2022',
    hour: '18h00',
    // participants: DUMMY_USERS,
    // responsable: ORGA,
    image: 'assets/images/eliasson.jpg',
  ),
  EventItem(
 //   id: 'Ev5',
    name: 'Engadin Art Talks',
    place: 'Zürich',
    date: '27.01.2022',
    hour: '16h00',
    // participants: DUMMY_USERS,
    // responsable: ORGA,
    image: 'assets/images/EngadinArtTalks.jpg',
  ),
  EventItem(
 //   id: 'Ev6',
    name: 'Artgenève',
    place: 'Genève',
    date: '1.02.2022',
    hour: '20h00',
    // participants: DUMMY_USERS,
    // responsable: ORGA,
    image: 'assets/images/artGeneve.jpg',
  ),
  EventItem(
 //   id: 'Ev7',
    name: 'Abraham Cruzvillegas: Social Tissue',
    place: 'Zürich',
    date: '16.02.2022',
    hour: '18h00',
 //   participants: DUMMY_USERS,
 //   responsable: ORGA,
    image: 'assets/images/cruzvillegas.jpg',
  ),
  EventItem(
 //   id: 'Ev8',
    name: 'Museumnight Bern',
    place: 'Berne',
    date: '16.03.2022',
    hour: '18h00',
 //   participants: DUMMY_USERS,
 //   responsable: ORGA,
    image: 'assets/images/museumNight.jpg',
  ),
];
