/*import 'package:art_events/dummy_users.dart';
import './models/event.dart';

const DUMMY_EVENTS = const [
  Event(
    idEvent: 'Ev1',
    name: 'Performance Christian Marclay',
    place: 'Bâle',
    date: '26.01.2022',
    hour: '19h00',
    image: 'assets/images/schuerpf.jpg',
  ),
  Event(
    idEvent: 'Ev2',
    name: 'Beyeler Foundation Georg Baselitz',
    place: 'Bâle',
    date: '21.01.2022',
    hour: '18h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/beyeler.jpg',
  ),
  Event(
    idEvent: 'Ev3',
    name: 'Art-à-Porter',
    place: 'Genève',
    date: '31.01.2022',
    hour: '10h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/artAporter.jpg',
  ),
  Event(
    idEvent: 'Ev4',
    name: 'Olafur Eliasson: Objects efined by activity',
    place: 'Genève',
    date: '23.01.2022',
    hour: '18h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/eliasson.jpg',
  ),
  Event(
    idEvent: 'Ev5',
    name: 'Engadin Art Talks',
    place: 'Zürich',
    date: '27.01.2022',
    hour: '16h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/EngadinArtTalks.jpg',
  ),
  Event(
    idEvent: 'Ev6',
    name: 'Artgenève',
    place: 'Genève',
    date: '1.02.2022',
    hour: '20h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/artGeneve.jpg',
  ),
  Event(
    idEvent: 'Ev7',
    name: 'Abraham Cruzvillegas: Social Tissue',
    place: 'Zürich',
    date: '16.02.2022',
    hour: '18h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/cruzvillegas.jpg',
  ),
  Event(
    idEvent: 'Ev8',
    name: 'Museumnight Bern',
    place: 'Berne',
    date: '16.03.2022',
    hour: '18h00',
    participants: DUMMY_USERS,
    responsable: ORGA,
    image: 'assets/images/museumNight.jpg',
  ),
];
*/